[project]
name = "ansci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.4.8",
    "pydantic (>=2.11.7,<3.0.0)",
]
